# Generated by Django 6.0.6 on 2026-06-05 20:08

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='phoneotp',
            new_name='accounts_ph_phone_n_7bb488_idx',
            old_name='accounts_ph_phone_n_3a2b8c_idx',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='school_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.schoolclass'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, to='classes.schoolclass'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
